INHERIT: docs/common/config.yml

site_name: "Notes"
site_url: "https://redtide.github.io/notes"
site_description: "Shared notes"

#copyright: "Copyright &copy; 2019 - 2023 redtide"
#repo_name: "GitHub"
#repo_url: "https://github.com/redtide/notes"

extra:
  homepage: "/notes/en/"
  social:
  - icon: "fontawesome/brands/github"
    link: "https://github.com/redtide/notes"
    name: "Notes on GitHub"

#plugins:
#  with-pdf: {}

not_in_nav: |
  common/README.md
  index.md

nav:
- redtide.github.io:   "https://redtide.github.io"
- "en/index.md"
- Other Docs:
  - Behringer X-Air:   "https://redtide.github.io/wiki-x-air/"
  - CppCoreGuidelines: "https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines"
  - SFZ Format:        "https://sfzformat.github.io/"
- CI:
  - "en/ci/appveyor.md"
  - "en/ci/travis.md"
- Git:
  - "en/git/branches.md"
  - "en/git/commits.md"
  - "en/git/orphan-branch.md"
  - "en/git/push-and-pull.md"
  - "en/git/rebase.md"
  - "en/git/remotes.md"
  - "en/git/submodules.md"
- GitHub:
  - "en/github/rest-api.md"
- Jekyll:
  - "en/jekyll/rvm.md"
  - "en/jekyll/syntax-highlighting.md"
- MKDocs:
  - "en/mkdocs/assignments.md"
- Android:
  - "en/android/custom-rom.md"
- Linux:
  - Arch:
    - External Links:
      - DevTools:
        - Repository: "https://gitlab.archlinux.org/archlinux/devtools"
        - Manual: "https://man.archlinux.org/man/devtools.7.en"
        - Vultr Article: "https://www.vultr.com/docs/using-devtools-on-arch-linux/"
      - Other Tools:
        - namcap: "https://man.archlinux.org/man/namcap.1"
        - updpkgsums: "https://man.archlinux.org/man/updpkgsums.8.en"
      - Package Guidelines: "https://wiki.archlinux.org/title/Arch_package_guidelines"
      - Wiki: "https://wiki.archlinux.org/"
    - "en/linux/arch/aur.md"
    - "en/linux/arch/pacman.md"
  - "en/linux/appimage.md"
  - "en/linux/macos-windows-icons.md"
  - LXQt:
    - "en/lxqt/xdg-desktop-portal.md"
- macOS:
  - "en/macos/dmg.md"
- Windows:
  - "en/windows/innosetup.md"
  - "en/windows/mingw-w64.md"
- Qt:
  - "en/qt/qtcreator.md"
  - "en/qt/android.md"
  - "en/qt/translations.md"
  - "en/qt/archive/bluetooth-modules.md"
  - "en/qt/archive/develop-android-apps-with-qt.md"
- OpenSUSE Build Service:
  - "en/obs/index.md"
- VirtualBox:
  - "en/virtualbox.md"
